name: Insta Mover

on:
  push:
    branches: [master]
  schedule:
    - cron: '*/15 * * * *'

# concurrency:
#   group: ${{ github.workflow }}
#   cancel-in-progress: true

jobs:
  pre-job-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout fzbot
      uses: actions/checkout@v3
      with:
        ref: fzbot
    - name: Check parallel run
      run: |
        git config user.email afzalex.store@gmail.com
        git config user.name "afzalex fzbot"
        if [[ -e IN_PROGRESS_FLAG ]]; then
          echo "IN_PROGRESS_FLAG found : need to explicitly remove it or wait for other job to complete"
          exit 1
        fi
    - name: Add progress flag
      run: |
        touch IN_PROGRESS_FLAG
        git add IN_PROGRESS_FLAG
        git commit -m "fzbot IN_PROGRESS_FLAG at $(date)"
        git push
  move-to-crnt:
    needs: pre-job-check
    runs-on: ubuntu-latest
    env:
      IG_COOKIE_VALUE: ${{ secrets.IG_COOKIE_VALUE }}
      IG_CSRFTOKEN: ${{ secrets.IG_CSRFTOKEN }}
      IG_ASBD_ID: ${{ vars.IG_ASBD_ID }}
      IG_REFERER_01: ${{vars.IG_REFERER_01}}
      CRNT_MOVE_RATE: ${{vars.CRNT_MOVE_RATE}}
      CRNT_FAIL_COUNT_TO_EXIT: ${{vars.CRNT_FAIL_COUNT_TO_EXIT}}
    steps:
    - name: Checkout fzbot
      uses: actions/checkout@v3
      with:
        ref: fzbot
    - name: Reset fzbot
      run: |
        git config user.email afzalex.store@gmail.com
        git config user.name "afzalex fzbot"
        fzbotVersion="$(( $( cat fzbot-version.txt ) + 1 ))"
        echo "fzbotVersion=${fzbotVersion}" >> $GITHUB_ENV
        git fetch
        git reset --hard origin/master
    - name: Move From Saved To crnt
      run: |
        ./move-saved-to-crnt.sh
    - name: Updating fzbot
      run: |
        echo "${fzbotVersion}" > fzbot-version.txt
        git add *
        git commit -m "fzbot Updated : v${fzbotVersion} at $(date)"
        git push -f